version: '3'
services:
  marqo:
    image: marqoai/marqo:latest
    ports:
      - "8882:8882"

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - marqo

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
